name: CI

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        run: echo Hello, world!

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: yongwon
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git pull origin ${{ github.ref_name }}
            docker-compose down ${{ secrets.DOCKER_IMAGE_NAME }}
            docker-compose build ${{ secrets.DOCKER_IMAGE_NAME }}
            docker-compose up -d ${{ secrets.DOCKER_IMAGE_NAME }}
